ServerEvents.tags('item', event => {
    event.add('forge:wires/high_current', 'createaddition:electrum_wire')
    event.add('forge:wires/high_current', 'createaddition:gold_wire')
    event.add('createaddition:spools/high_current', 'createaddition:gold_spool')
    event.add('createaddition:spools/high_current', 'createaddition:electrum_spool')
    event.add('forge:raw_materials/tungsten', 'createloveandwar:raw_tungsten')
    event.add('forge:raw_materials', 'createloveandwar:raw_tungsten')
    event.add('forge:storage_blocks/raw_nickel', 'kubejs:block_raw_nickel')
    event.add('forge:storage_blocks/raw_lithium', 'kubejs:block_raw_lithium')
    event.add('forge:storage_blocks/raw_tungsten', 'createloveandwar:raw_tungsten_block')
    const dye = ['white', 'red', 'orange', 'yellow', 'green', 'lime', 'light_blue', 'cyan', 'blue', 'purple', 'magenta', 'pink', 'light_gray', 'gray', 'brown', 'black']
    for (let i = 0; i < dye.length; i++) {
        event.add('created_dd:padded_tiled_rubber', 'create_dd:' + dye[i] + '_padded_tiled_rubber')
        event.add('created_dd:padded_rubber', 'create_dd:' + dye[i] + '_padded_rubber')
        event.add('created_dd:padded_rubber_stairs', 'create_dd:' + dye[i] + '_padded_rubber_stairs')
        event.add('created_dd:padded_rubber_slab', 'create_dd:' + dye[i] + '_padded_rubber_slab')
        event.add('created_dd:padded_mosaic_rubber', 'create_dd:' + dye[i] + '_padded_mosaic_rubber')
        event.add('createloveandwar:plastic', 'createloveandwar:' + dye[i] + '_plastic')
        event.add('ad_astra:industrial_lamp', 'ad_astra:' + dye[i] + '_industrial_lamp')
        event.add('ad_astra:small_industrial_lamp', 'ad_astra:small_' + dye[i] + '_industrial_lamp')
        event.add('tfmg:caution_block', 'tfmg:' + dye[i] + '_caution_block')
    }
    event.add('create_dd:asphalt_blocks', 'tfmg:asphalt')
    event.add('createloveandwar:plastic', 'tfmg:plastic_block')
    event.add('created_dd:padded_tiled_rubber', 'create_dd:padded_tiled_rubber')
    event.add('created_dd:padded_rubber', 'create_dd:padded_rubber')
    event.add('created_dd:padded_rubber_stairs', 'create_dd:padded_rubber_stairs')
    event.add('created_dd:padded_rubber_slab', 'create_dd:padded_rubber_slab')
    event.add('created_dd:padded_mosaic_rubber', 'create_dd:padded_mosaic_rubber')
    event.add('forge:dyes/yellow', 'tfmg:sulfur_dust')
    const types = ['_stairs', '_slab', '_wall']
    for (let i = 0; i < types.length; i++) {
        event.add('alexscaves:stone_types/galena', 'alexscaves:galena' + types[i])
        event.add('alexscaves:stone_types/galena', 'alexscaves:galena_brick' + types[i])
        event.add('alexscaves:stone_types/limestone', 'alexscaves:limestone' + types[i])
        event.add('alexscaves:stone_types/limestone', 'alexscaves:smooth_limestone' + types[i])
    }
    event.add('alexscaves:stone_types/galena', 'alexscaves:packed_galena')
    event.add('alexscaves:stone_types/galena', 'alexscaves:galena')
    event.add('alexscaves:stone_types/galena', 'alexscaves:galena_pillar')
    event.add('alexscaves:stone_types/limestone', 'alexscaves:limestone')
    event.add('alexscaves:stone_types/limestone', 'alexscaves:limestone_chiseled')
    event.add('alexscaves:stone_types/limestone', 'alexscaves:limestone_pillar')
    event.add('alexscaves:stone_types/galena', 'alexscaves:galena_bricks')
    event.add('alexscaves:stone_types/limestone', 'alexscaves:smooth_limestone')
})