const dyes = ['white', 'red', 'orange', 'yellow', 'green', 'lime', 'light_blue', 'cyan', 'blue', 'purple', 'magenta', 'pink', 'light_gray', 'gray', 'brown', 'black']
const gas = ['neon', 'carbon_dioxide', 'lpg', 'propylene', 'ethylene', 'butane', 'propane', 'air']
ServerEvents.recipes(event => {
    event.remove({ id: 'create:milling/lapis_lazuli'})
    event.remove({ id: 'create_dd:cog_crank'})
    event.remove({ id: 'create_dd:crafting/kinetics/redstone_divider'})
    event.remove({ id: 'create_dd:crafting/kinetics/inverse_box'})
    event.remove({ type: 'create_dd:seething', output: 'create_dd:diamond_shard'})
    event.remove({ type: 'create_dd:seething', output: "minecraft:netherite_scrap"})
    event.remove({ id: 'create_dd:crafting/fan_catalyst/blasting_sail'})
    event.remove({ id: 'create_dd:crafting/fan_catalyst/freezing_sail'})
    event.remove({ id: 'create_dd:crafting/fan_catalyst/haunting_sail'})
    event.remove({ id: 'create_dd:crafting/fan_catalyst/sanding_sail'})
    event.remove({ id: 'create_dd:crafting/fan_catalyst/smoking_sail'})
    event.remove({ id: 'create_dd:crafting/fan_catalyst/splashing_sail'})
    event.remove({ id: 'create_dd:mechanical_crafting/gilded_rose_axe'})
    event.remove({ id: 'create_dd:mechanical_crafting/gilded_rose_hoe'})
    event.remove({ id: 'create_dd:mechanical_crafting/gilded_rose_pickaxe'})
    event.remove({ id: 'create_dd:mechanical_crafting/gilded_rose_shovel'})
    event.remove({ id: 'create_dd:mechanical_crafting/gilded_rose_sword'})
    event.remove({ id: 'create_dd:crafting/equipment/magnet'})
    event.remove({ id: 'create_dd:crafting/equipment/flipped_magnet'})
    event.remove({ output: 'create_dd:fluid_reservoir'})
    event.remove({ output: 'create_dd:item_stockpile'})
    event.remove({ id: 'create_dd:mixing/raw_rubber'})
    for (let i = 0; i < dyes.length; i++) {
        event.remove({ id: 'create_dd:crafting/decor/' + dyes[i] + '_asphalt_block'})
    }
    event.remove({ mod: 'immersive_aircraft'})
    event.remove({ type: 'createloveandwar:fractional_distillation'})
    event.remove({ id: 'createloveandwar:mixing/bitumen_from_charcoal'})
    event.remove({ id: 'createloveandwar:mixing/bitumen'})
    event.remove({ id: 'createloveandwar:mixing/kerosene_from_diesel'})
    event.remove({ id: 'createloveandwar:mixing/ethylene_from_kerosene'})
    event.remove({ id: 'createloveandwar:mixing/polymer'})
    event.remove({ id: 'createloveandwar:robot_dog_spawn_egg'})
    event.remove({ output: 'createloveandwar:steel_ingot'})
    event.remove({ id: 'createloveandwar:pressing/netherite_sheet'})
    event.remove({ id: 'createloveandwar:crafting/thermostat'})
    event.remove({ id: 'createloveandwar:compressing/bitumen'})
    event.remove({ output: 'createloveandwar:block_of_polymer'})
    event.remove({ id: 'createloveandwar:crafting/white_plastic'})
    event.remove({ type: 'create:mixing', mod: 'createloveandwar'})
    event.remove({ id: 'createloveandwar:compressing/duraplas_ingot'})
    event.remove({ id: 'createloveandwar:compressing/fuel_pellet'})
    event.remove({id: 'createloveandwar:blasting/brass_blasting'})
    event.remove({id: 'createloveandwar:crafting/brass_mix'})
    event.remove({ id: 'tfmg:mixing/liquid_plastic_from_propylene'})
    event.remove({ id: 'tfmg:mixing/liquid_plastic_from_ethylene'})
    event.remove({ id: 'minecraft:gunpowder'})
    event.remove({ id: 'tfmg:mixing/copper_sulfate'})
    event.remove({ id: 'tfmg:crushing/copper_sulfate'})
    for (let j = 0; j < gas.length; j++) {
        event.remove({ id: 'tfmg:filling/' + gas[j] + '_tank'})
    }
    event.remove({ id: 'tfmg:mixing/neon'})
    event.remove({ id: 'tfmg:sequenced_assembly/heavy_plate'})
    event.remove({ id: 'tfmg:stonecutting/aluminum_wire'})
    event.remove({ id: 'tfmg:stonecutting/copper_wire'})
    event.remove({ id: 'tfmg:mixing/sulfuric_acid'})
    event.remove({ id: 'tfmg:stonecutting/rebar'})
    event.remove({ output: 'tfmg:copper_cable'})
    event.remove({id: 'tfmg:distillation/crude_oil_no_naphtha'})
    event.remove({id: 'tfmg:crafting/transistor'})
    event.remove({ output: 'createaddition:modular_accumulator'})
    event.remove({ id: 'vintageimprovements:pressurizing/sulfur_trioxide'})
    event.remove({ id: 'vintageimprovements:pressurizing/sulfur_trioxide_alt'})
    event.remove({ id: 'vintageimprovements:pressurizing/sulfur_dioxide'})
    event.remove({ id: 'vintageimprovements:pressurizing/sulfuric_acid'})
    event.remove({ id: 'vintageimprovements:pressurizing/copper_sulfate'})
    event.remove({ output: 'vintageimprovements:steel_rod'})
    event.remove({ output: 'vintageimprovements:osmium_sheet'})
    event.remove({ id: 'createaddition:mechanical_crafting/alternator'})
    event.remove({ id: 'createaddition:mechanical_crafting/electric_motor'})
    event.remove({ id: 'createaddition:crafting/capacitor_1'})
    event.remove({ id: 'createaddition:crafting/capacitor_2'})
    event.remove({ id: 'createaddition:crafting/small_connector_copper'})
    event.remove({id: 'createaddition:crafting/small_light_connector'})
    event.remove({ output: 'createaddition:biomass'})
    event.remove({ output: 'create_connected:vertical_six_way_gearbox'})
    event.remove({ output: 'create_connected:six_way_gearbox'})
    event.remove({ id: 'create_connected:sequenced_assembly/control_chip'})
    event.remove({ id: 'create_connected:crafting/kinetics/encased_chain_cogwheel'})
    event.remove({ output: 'create_connected:parallel_gearbox'})
    event.remove({ output: 'create_connected:vertical_parallel_gearbox'})
    event.remove({ output: 'create_connected:brass_gearbox'})
    event.remove({ output: 'create_connected:vertical_brass_gearbox'})
    event.remove({ output: 'create_connected:sequenced_pulse_generator'})
    event.remove({ id: 'create_connected:item_application/seething_catalyst_from_empty'})
    event.remove({ output: 'refinedstorage:silicon'})
    event.remove({ id: 'refinedstorage:quartz_enriched_iron'})
    event.remove({ id: 'refinedstorage:machine_casing'})
    event.remove({ id: 'refinedstorage:basic_processor'})
    event.remove({ id: 'refinedstorage:improved_processor'})
    event.remove({ id: 'refinedstorage:advanced_processor'})
    event.remove({ id: 'refinedstorage:raw_basic_processor'})
    event.remove({ id: 'refinedstorage:raw_improved_processor'})
    event.remove({ id: 'refinedstorage:raw_advanced_processor'})
    event.remove({ id: 'refinedstorage:wrench'})
    event.remove({ id: 'createteleporters:quantum_casing_recipe'})
    event.remove({ id: 'createteleporters:advanced_part_recipe'})
    event.remove({ id: 'createteleporters:quantum_mechanism_recipe'})
    event.remove({ mod: 'toms_storage'})
    event.remove({ id: 'sophisticatedbackpacks:filter_upgrade'})
    event.remove({ id: 'sophisticatedbackpacks:advanced_filter_upgrade'})
    event.remove({ id: 'sophisticatedbackpacks:pickup_upgrade'})
    event.remove({ id: 'sophisticatedbackpacks:magnet_upgrade'})
    event.remove({ id: 'sophisticatedbackpacks:advanced_magnet_upgrade'})
    event.remove({ id: 'sophisticatedbackpacks:tank_upgrade'})
    event.remove({ id: 'sophisticatedbackpacks:battery_upgrade'})
    event.remove({ id: 'sophisticatedbackpacks:pump_upgrade'})
    event.remove({ id: 'sophisticatedbackpacks:advanced_pump_upgrade'})
    event.remove({ id: 'create_dd:seething/mekanism/crushed_raw_lead'})
    event.remove({ id: 'create:smelting/ingot_lead_compat_mekanism'})
    event.remove({ id: 'create:blasting/ingot_lead_compat_mekanism'})
    event.remove({ id: 'mekanism:processing/lead/storage_blocks/from_ingots'})
    event.remove({ id: 'mekanism:processing/lead/ingot/from_block'})
    event.remove({ id: 'mekanism:processing/steel/ingot/from_block'})
    event.remove({ id: 'mekanism:storage_blocks/steel'})
    event.remove({ output: 'mekanism:ingot_steel'})
    event.remove({ output: 'mekanism:enriched_iron' })
    event.remove({ id: 'mekanism:infusion_conversion/carbon/from_charcoal'})
    event.remove({ id: 'mekanism:infusion_conversion/carbon/from_charcoal_block'})
    event.remove({ id: 'mekanism:infusion_conversion/carbon/from_coal' })
    event.remove({ id: 'mekanism:infusion_conversion/carbon/from_coal_block'})
    event.remove({ output: 'mekanism:basic_control_circuit'})
    event.remove({ output: 'mekanism:alloy_reinforced'})
    event.remove({ output: 'mekanism:alloy_atomic'})
    event.remove({ output: 'mekanism:elite_control_circuit'})
    event.remove({ output: 'mekanism:advanced_control_circuit'})
    event.remove({ output: 'mekanism:ultimate_control_circuit'})
    event.remove({ id: 'mekanism:processing/steel/enriched_iron_to_dust'})
    event.remove({ id: 'mekanism:metallurgic_infuser'})
    event.remove({ id: 'mekanismgenerators:generator/heat'})
    event.remove({ output: 'mekanism:basic_mechanical_pipe'})
    event.remove({ output: 'mekanism:basic_universal_cable'})
    event.remove({ output: 'mekanism:basic_pressurized_tube'})
    event.remove({ output: 'mekanism:basic_logistical_transporter'})
    event.remove({ output: 'mekanism:basic_thermodynamic_conductor'})
    event.remove({ output: 'mekanism:energy_tablet'})
    event.remove({ output: 'mekanism:basic_energy_cube'})
    event.remove({ output: 'mekanism:advanced_energy_cube'})
    event.remove({ output: 'mekanism:basic_chemical_tank'})
    event.remove({ output: 'mekanism:advanced_chemical_tank'})
    event.remove({ output: 'mekanism:basic_fluid_tank'})
    event.remove({ output: 'mekanism:advanced_fluid_tank'})
    event.remove({ id: 'mekanism:configurator'})
    event.remove({id: 'mekanism:enrichment_chamber'})
    event.remove({ id: 'mekanism:processing/lead/raw_storage_blocks/from_raw'})
    event.remove({ id: 'mekanism:combiner'})
    event.remove({ id: 'mekanism:precision_sawmill'})
    const logs = ['oak', 'spruce', 'birch', 'jungle', 'acacia', 'dark_oak', 'mangrove', 'cherry', 'warped', 'crimson', 'glacian']
    for (let i = 0; i < logs.length; i++) {
        event.remove({ id: 'mekanism:sawing/log/' + logs[i]})
    }
    event.remove({ id: 'mekanism:sawing/bamboo_block'})
    event.remove({ id: 'mekanism:osmium_compressor'})
    event.remove({ id: 'mekanism:purification_chamber'})
    event.remove({ id: 'mekanism:chemical_injection_chamber'})
    event.remove({id: 'mekanism:pigment_extractor'})
    event.remove({id: 'mekanism:pigment_mixer'})
    event.remove({id: 'mekanism:electric_pump'})
    event.remove({id: 'mekanism:fluidic_plenisher'})
    event.remove({id: 'mekanism:chemical_infuser'})
    event.remove({id: 'mekanism:rotary/sulfuric_acid'})
    event.remove({id: 'mekanism:rotary/ethene'})
    event.remove({id: 'mekanism:resistive_heater'})
    event.remove({id: 'mekanism:fuelwood_heater'})
    event.remove({id: 'mekanism:nutritional_liquifier'})
    event.remove({id: 'mekanism:modification_station'})
    event.remove({id: 'mekanism:chemical_dissolution_chamber'})
    event.remove({id: 'mekanism:chemical_washer'})
    event.remove({id: 'mekanism:chemical_crystallizer'})
    event.remove({id: 'mekanism:seismic_vibrator'})
    event.remove({id: 'mekanism:isotopic_centrifuge'})
    event.remove({id: 'mekanism:electrolytic_separator'})
    event.remove({id: 'mekanism:seismic_reader'})
    event.remove({id: 'mekanism:laser'})
    event.remove({id: 'mekanism:digital_miner'})
    event.remove({id: 'mekanism:qio_drive_array'})
    event.remove({id: 'mekanism:qio_redstone_adapter'})
    event.remove({id: 'mekanism:qio_exporter'})
    event.remove({id: 'mekanism:qio_importer'})
    event.remove({id: 'mekanism:qio_dashboard'})
    event.remove({id: 'mekanism:bin/basic'})
    event.remove({id: 'mekanism:steel_casing'})
    event.remove({id: 'mekanism:dynamic_tank'})
    event.remove({id: 'mekanism:thermal_evaporation/valve'})
    event.remove({id: 'mekanism:thermal_evaporation/controller'})
    event.remove({id: 'mekanism:sps_port'})
    event.remove({id: 'mekanism:teleporter'})
    event.remove({id: 'mekanism:robit'})
    event.remove({id: 'mekanism:portable_qio_dashboard'})
    event.remove({id: 'mekanism:qio_drive_base'})
    event.remove({id: 'mekanism:qio_drive_hyper_dense'})
    event.remove({id: 'mekanism:qio_drive_time_dilating'})
    event.remove({id: 'mekanism:qio_drive_supermassive'})
    event.remove({id: 'mekanism:portable_qio_dashboard'})
    event.remove({id: 'mekanism:qio_redstone_adapter'})
    event.remove({id: 'mekanism:atomic_disassembler'})
    event.remove({id: 'mekanism:flamethrower'})
    event.remove({id: 'mekanism:scuba_mask'})
    event.remove({id: 'mekanism:scuba_tank'})
    event.remove({id: 'mekanism:jetpack'})
    event.remove({id: 'mekanism:chargepad'})
    event.remove({id: 'mekanism:rotary_condensentrator'})
    event.remove({id: 'mekanism:reaction/substrate/ethene_oxygen'})
    event.remove({id: 'mekanism:formulaic_assemblicator'})
    event.remove({id: 'mekanism:gas_conversion/flint_to_oxygen'})
    event.remove({id: 'mekanism:gas_conversion/salt_to_hydrogen_chloride'})
    event.remove({id: 'mekanism:gas_conversion/sulfur_to_sulfuric_acid'})
    event.remove({id: 'mekanismgenerators:solar_panel'})
    event.remove({id: 'mekanismgenerators:generator/gas_burning'})
    event.remove({id: 'mekanismgenerators:generator/bio'})
    event.remove({id: 'mekanismgenerators:generator/advanced_solar'})
    event.remove({id: 'mekanismgenerators:generator/wind'})
    event.remove({id: 'mekanismgenerators:turbine/rotor'})
    event.remove({id: 'mekanismgenerators:rotational_complex'})
    event.remove({id: 'mekanismgenerators:electromagnetic_coil'})
    event.remove({ id: 'create:crushing/osmium_ore'})
    event.remove({ id: 'create:crushing/tin_ore'})
    event.remove({ id: 'create:crushing/uranium_ore'})
    event.remove({ id: 'create:crushing/nickel_ore'})
    event.remove({ id: 'create:crushing/lead_ore'})
    event.remove({ id: 'createloveandwar:crushing/deepslate_sulphur_ore'})
    event.remove({ id: 'createloveandwar:crushing/sulphur_ore'})
    event.remove({ id: 'createloveandwar:crushing/tungsten_ore'})
    event.remove({ id: 'ad_astra:coal_generator'})
    event.remove({ output: 'ad_astra:steel_plate'})
    event.remove({ id: 'ad_astra:steel_rod'})
    event.remove({ id: 'ad_astra:photovoltaic_etrium_cell'})
    event.remove({ id: 'ad_astra:etrionic_blast_furnace'})
    event.remove({ output: 'ad_astra:steel_ingot'})
    event.remove({id: 'ad_astra:steel_block'})
    event.remove({ id: 'ad_astra:alloying/steel_ingot_from_alloying_iron_ingot_and_coals'})
    event.remove({ id: 'ad_astra:steel_nugget'})
    event.remove({ id: 'ad_astra:compressor'})
    event.remove({ id: 'ad_astra:compressing/iron_plate_from_compressing_iron_block'})
    event.remove({ id: 'ad_astra:compressing/iron_plate_from_compressing_iron_ingot'})
    event.remove({ id: 'ad_astra:compressing/steel_plate_from_compressing_steel_blocks'})
    event.remove({ id: 'ad_astra:compressing/steel_plate_from_compressing_steel_ingots'})
    event.remove({id: 'ad_astra:solar_panel'})
    event.remove({id: 'ad_astra:fuel_refinery'})
    event.remove({id: 'ad_astra:nasa_workbench'})
    event.remove({id: 'ad_astra:oxygen_loader'})
    event.remove({id: 'ad_astra:etrionic_capacitor'})
    event.remove({id: 'ad_astra:energizer'})
    event.remove({id: 'ad_astra:water_pump'})
    event.remove({id: 'ad_astra:cryo_freezer'})
    event.remove({id: 'ad_astra:steel_tank'})
    event.remove({id: 'ad_astra:desh_tank'})
    event.remove({id: 'ad_astra:ostrum_tank'})
    event.remove({id: 'ad_astra:calorite_tank'})
    event.remove({id: 'ad_astra:steel_engine'})
    event.remove({id: 'ad_astra:desh_engine'})
    event.remove({id: 'ad_astra:ostrum_engine'})
    event.remove({id: 'ad_astra:calorite_engine'})
    event.remove({type: 'ad_astra:nasa_workbench'})
    event.remove({id: 'ad_astra:refining/fuel_from_refining_oil'})
    event.remove({id: 'ad_astra:fluid_pipe_duct'})
    event.remove({id: 'ad_astra:steel_cable'})
    event.remove({id: 'ad_astra:desh_cable'})
    event.remove({id: 'ad_astra:desh_fluid_pipe'})
    event.remove({id: 'ad_astra:ostrum_fluid_pipe'})
    event.remove({id: 'ad_astra:wrench'})
    event.remove({id: 'ad_astra:fan'})
    event.remove({id: 'ad_astra:engine_frame'})
    event.remove({id: 'ad_astra:tier_1_rover'})
    event.remove({ id: 'create:pressing/desh_ingot'})
    event.remove({ id: 'create:pressing/ostrum_ingot'})
    event.remove({ id: 'create:pressing/calorite_ingot'})
    event.remove({id: 'moreburners:copper_coil'})
    event.remove({id: 'moreburners:electric_burner'})
    event.remove({id: 'moreburners:resistance_coil'})
    event.remove({id: 'createteleporters:custom_portal_recipe'})
    event.remove({id: 'createteleporters:gravity_stab_recipe'})
    event.remove({id: 'flansmod:rainbow_paintcan_a'})
    event.remove({id: 'flansmod:rainbow_paintcan_b'})
    event.remove({id: 'flansmod:gun_painting_table'})
    event.remove({id: 'useless_sword:message_in_a_sword_recipe'})
    event.remove({id: "useless_sword:neptunium_grab_sword_recipe"})
    event.remove({id: "useless_sword:rotten_fish_rapier_recipe"})
    event.remove({id: "useless_sword:hemolymph_broadsword_recipe"})
    event.remove({id: "useless_sword:guster_sword_recipe"})
    event.remove({id:"useless_sword:tooth_glaive_recipe"})
    event.remove({id:"useless_sword:dna_cutter_recipe"})
    event.remove({id:"useless_sword:naga_slicer_recipe"})
    event.remove({id: "useless_sword:pesting_rapier_recipe"})
    event.remove({id: "useless_sword:vexswordcraft"})
    event.remove({id:"useless_sword:life_draining_sword_recipe"})
})
